export const allColors = {
    light: {
        accentText: '#3489E4',
        buttonText: '#FFFFFF',
        regularText: '#4E4E4E',
        titleText: '#000000',
        textAccentButton: '#155249',
        modalBackground: '#00000080',
        icon: '#000000',
        error: '#FF5010',
        low: '#2ECC71',
        medium: '#F7DC6F',
        high: '#E74C3C',
        shadow: '#bababa',
        background: '#E4ECF9',
        card: '#FFFFFF',
        lightButton: '#EDEDED',
        inactiveText: '#979797',
        accentColorLight1: '#C4AFF0',
        accentColorDark1: '#3F2150',
        accentColorLight: '#C9D3EA',
        accentColorDark: '#384F6A',
    },
    dark: {
        accentText: '#4C6EBB',
        buttonText: '#FFFFFF',
        regularText: '#f0f0f5',
        titleText: '#e9e9f0',
        textAccentButton: '#155249',
        modalBackground: '#00000080',
        icon: '#e9e9f0',
        error: '#FF5010',
        low: '#2ECC71',
        medium: '#F7DC6F',
        high: '#E74C3C',
        shadow: '#bababa',
        background: '#12121a',
        card: '#EAEDED',
        inactiveText: '#e6e6fc',
        accentColorLight1: '#C4AFF0',
        accentColorDark1: '#3F2150',
        accentColorLight: '#384F6A',
        accentColorDark: '#C4AFF0',
    },
};
